### ISSUE TITLE
main.py uses requests library

### ISSUE THREAD

**Issue by wdowns101** [wdowns101/ITSV412Group4-Project-3#2]
we need to change our code to use the url.lib so that would be the first part of the code that needs changing

**Comment by alyssianav** [comment]
Just tried to fix the issue, let me know if I need to look at it again!

**Comment by sanawnglasham** [comment]
I have checked the file, and ran it. Found "FileNotFoundError".

**Comment by alyssianav** [comment]
The url.lib part of the code seems to be working now :) Will close the issue
